version: '3'
services:

  elasticsearch:
    image: elasticsearch:7.13.0
    environment:
      - discovery.type=single-node
    volumes:
      - data:/usr/share/elasticsearch/data

  postgres:
    image: postgres:13.3-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - pg-data:/var/lib/postgresql/data

  django:
    container_name: elastic_drf_example_django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - elasticsearch

volumes:
  pg-data:
  data:
